apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-nk9ds
  creationTimestamp: '2025-04-10T15:50:59Z'
  finalizers:
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
    - wrangler.cattle.io/cloud-config-secret-remover
  generation: 2
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint: {}
          f:rkeConfig:
            .: {}
            f:chartValues:
              .: {}
              f:rke2-calico: {}
            f:dataDirectories: {}
            f:etcd:
              .: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
            f:machinePoolDefaults: {}
            f:machineSelectorConfig: {}
            f:registries: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2025-04-10T15:51:00Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
      manager: rancher-v2.10.3-secret-migrator
      operation: Update
      time: '2025-04-10T15:51:00Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:fleetWorkspaceName: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2025-04-10T15:56:56Z'
  name: assignhome
  namespace: fleet-default
  resourceVersion: '6424'
  uid: 89cf580f-21a4-4f7f-99ca-4e5f8a4fce56
spec:
  kubernetesVersion: v1.31.7+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    dataDirectories: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: assignhome-kubeconfig
  clusterName: c-m-tk9wpplh
  conditions:
    - lastUpdateTime: '2025-04-10T15:56:43Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2025-04-10T15:50:59Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2025-04-10T15:56:44Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2025-04-10T15:56:56Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2025-04-10T15:50:59Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2025-04-10T15:51:00Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2025-04-10T15:51:00Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2025-04-10T15:56:56Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2025-04-10T15:56:56Z'
      status: 'True'
      type: Provisioned
    - lastUpdateTime: '2025-04-10T15:56:56Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2025-04-10T15:51:00Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2025-04-10T15:51:01Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2025-04-10T15:51:01Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2025-04-10T15:51:01Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2025-04-10T15:51:01Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2025-04-10T15:51:01Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2025-04-10T15:51:01Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2025-04-10T15:51:01Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2025-04-10T15:56:39Z'
      status: 'True'
      type: Connected
    - status: Unknown
      type: PreBootstrapped
    - lastUpdateTime: '2025-04-10T15:56:28Z'
      status: 'True'
      type: AgentTlsStrictCheck
    - lastUpdateTime: '2025-04-10T15:56:28Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2025-04-10T15:56:31Z'
      status: 'True'
      type: AgentDeployed
    - lastUpdateTime: '2025-04-10T15:56:31Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2025-04-10T15:56:42Z'
      status: 'True'
      type: Waiting
  fleetWorkspaceName: fleet-default
  observedGeneration: 2
  ready: true
